# Prettier Configuration
# Schema: https://json.schemastore.org/prettierrc
# Docs: https://prettier.io/docs/options

printWidth: 100
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: always
proseWrap: preserve
htmlWhitespaceSensitivity: css
vueIndentScriptAndStyle: false
endOfLine: lf
embeddedLanguageFormatting: auto
singleAttributePerLine: false
objectWrap: preserve
experimentalTernaries: false
experimentalOperatorPosition: end
requirePragma: false
insertPragma: false
checkIgnorePragma: false
